export const productDetailsActionsTypes = {
    PRODUCT_DETAILS_REQUEST: "PRODUCT_DETAILS_REQUEST",
    PRODUCT_DETAILS_SUCCESS: "PRODUCT_DETAILS_SUCCESS",
    PRODUCT_DETAILS_FAIL: "PRODUCT_DETAILS_FAIL",
}