export const userActionsTypes = {
    SIGN_IN_USER_REQUEST: "SIGN_IN_USER_REQUEST",
    SIGN_IN_USER_SUCCESS: "SIGN_IN_USER_SUCCESS",
    SIGN_IN_USER_FAIL: "SIGN_IN_USER_FAIL",
    SIGN_UP_USER_REQUEST: "SIGN_UP_USER_REQUEST",
    SIGN_UP_USER_SUCCESS: "SIGN_UP_USER_SUCCESS",
    SIGN_UP_USER_FAIL: "SIGN_UP_USER_FAIL",
    EDIT_USER_REQUEST: "EDIT_USER_REQUEST",
    EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
    EDIT_USER_FAIL: "EDIT_USER_FAIL",
    LOG_OUT_USER: "LOG_OUT_USER",
} 