export const cartActionsTypes = {
    ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
    REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
    INCREASE_ITEM_QUANTITY: "INCREASE_ITEM_QUANTITY",
    DECREASE_ITEM_QUANTITY: "DECREASE_ITEM_QUANTITY",
}